services:
  db:
    image: postgres:17-alpine
    container_name: gerencia-rh-db
    restart: always
    environment:
       POSTGRES_USER: raifreire
       POSTGRES_PASSWORD: kaka22raisinho
       POSTGRES_DB: gerencia-rh-db
    ports:
      - "5432:5432"       
    volumes:
      - pgdata:/var/lib/postgresql/data
 
volumes:
  pgdata:
