# Generated by Django 4.2 on 2024-02-20 20:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_rename_aluno2_aluno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=254)),
                ('cpf', models.CharField(max_length=14)),
                ('data_nascimento', models.DateField()),
                ('matricula', models.IntegerField()),
                ('departamento', models.TextField(choices=[('FINACEIRO', 'FINACEIRO'), ('CENTRAL_ATENDIMENTO', 'CENTRAL DE ATENDIMENTO'), ('CENTRAL_INADIMPLENCIA', 'CENTRAL DE INADIMPLENCIA'), ('COBRANCA', 'COBRANÇA'), ('CONTROLE_QUALIDADE', 'CONTROLE DE QUALIDADE'), ('REAL_CREDIT', 'REAL CREDIT'), ('RELACIONAMENTO', 'RELACIONAMENTO'), ('COMERCIAL', 'COMERCIAL'), ('RH', 'RH'), ('DEP_PESSOAL', 'DEPARTAMENTO PESSOAL'), ('JURIDICO', 'JURIDICO'), ('CONTABIL', 'CONTABIL'), ('CENTRAL_VENDAS', 'CENTRAL DE VENDAS'), ('SUPORTE_ADM', 'SUPORTE ADM'), ('FRANQUIAS_DISTRIBUIDORES', 'FRANQUIAS / DISTRIBUIDORES'), ('GERENCIA_CORPORATIVA', 'GERENCIA CORPORATIVA'), ('DIRETORIA_EXECUTIVA', 'DIRETORIA EXECUTIVA')], default='', max_length=150)),
                ('data_entrada', models.DateField(default=datetime.datetime.now)),
                ('data_saida', models.DateField()),
                ('telefone', models.CharField(blank=True, max_length=15)),
                ('tel_familia', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('observacao', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ativo_inativo', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Aluno',
        ),
    ]
