# Generated by Django 4.2 on 2024-02-23 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_colaborador_classificacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='data_saida',
            field=models.DateField(blank=True),
        ),
    ]
