# Generated by Django 4.2 on 2024-02-27 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_colaborador_data_saida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='data_saida',
            field=models.DateField(blank=True, null=True),
        ),
    ]
