# Generated by Django 4.2 on 2024-03-06 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_colaborador_data_saida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='classificacao',
            field=models.TextField(choices=[('ESTAGIARIO', 'ESTAGIARIO'), ('FUNCIONARIO', 'FUNCIONARIO'), ('MEI', 'MEI')], default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='departamento',
            field=models.TextField(choices=[('FINACEIRO', 'FINACEIRO'), ('CENTRAL_ATENDIMENTO', 'CENTRAL DE ATENDIMENTO'), ('CENTRAL_INADIMPLENCIA', 'CENTRAL DE INADIMPLENCIA'), ('COBRANCA', 'COBRANÇA'), ('CONTROLE_QUALIDADE', 'CONTROLE DE QUALIDADE'), ('REAL_CREDIT', 'REAL CREDIT'), ('RELACIONAMENTO', 'RELACIONAMENTO'), ('COMERCIAL', 'COMERCIAL'), ('RH', 'RH'), ('DEP_PESSOAL', 'DEPARTAMENTO PESSOAL'), ('JURIDICO', 'JURIDICO'), ('CONTABIL', 'CONTABIL'), ('CENTRAL_VENDAS', 'CENTRAL DE VENDAS'), ('SUPORTE_ADM', 'SUPORTE ADM'), ('FRANQUIAS_DISTRIBUIDORES', 'FRANQUIAS / DISTRIBUIDORES'), ('GERENCIA_CORPORATIVA', 'GERENCIA CORPORATIVA'), ('DIRETORIA_EXECUTIVA', 'DIRETORIA EXECUTIVA'), ('INFORMATICA', 'INFORMÁTICA')], default='', max_length=150),
        ),
    ]
