# Generated by Django 4.2 on 2024-03-19 19:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_colaborador_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_contrato', models.CharField(max_length=50, unique=True)),
                ('num_contrato', models.CharField(max_length=100)),
                ('periodo', models.IntegerField()),
                ('data_inicio', models.DateField(default=datetime.datetime.now)),
                ('data_termino', models.DateField(blank=True, null=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.colaborador')),
            ],
        ),
    ]
