# Generated by Django 4.2 on 2024-03-19 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_contrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='colaborador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='main.colaborador'),
        ),
    ]
