# Generated by Django 4.2 on 2024-03-26 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_contrato_colaborador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='id_contrato',
        ),
        migrations.AddField(
            model_name='contrato',
            name='upload_contrato',
            field=models.FileField(default='2009', upload_to='uploads/% Y/% m/% d/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contrato',
            name='num_contrato',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='periodo',
            field=models.CharField(choices=[('1', 'PRIMEIRO'), ('2', 'SEGUNDO'), ('3', 'TERCEIRO'), ('4', 'QUARTO')], max_length=1),
        ),
    ]
