# Generated by Django 4.2 on 2024-03-26 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_contrato_id_contrato_contrato_upload_contrato_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='upload_contrato',
            field=models.FileField(blank=True, upload_to='uploads/% Y/% m/% d/'),
        ),
    ]
