# Generated by Django 4.2 on 2024-03-26 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_contrato_upload_contrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='num_contrato',
            field=models.CharField(max_length=50),
        ),
    ]
