# Generated by Django 4.2 on 2024-03-27 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_contrato_num_contrato'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colaborador',
            old_name='tel_familia',
            new_name='tel_auxiliar',
        ),
        migrations.AddField(
            model_name='colaborador',
            name='cpf_mae',
            field=models.CharField(default='000.999.000-23', max_length=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='colaborador',
            name='cpf_pai',
            field=models.CharField(default='222.111.333-32', max_length=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='colaborador',
            name='estado_civil',
            field=models.CharField(choices=[('SOLTEIRO', 'SOLTEIRO(a)'), ('CASADO', 'CASADO(a)'), ('DIVORCIADO', 'DIVORCIADO(a)'), ('SEPARADO', 'SEPARADO(a)'), ('VIUVO', 'VIUVO(a)')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='estado_naturalidade',
            field=models.CharField(default='pernambuco', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='colaborador',
            name='naturalidade',
            field=models.CharField(default='olinda', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='colaborador',
            name='nome_conjuge',
            field=models.CharField(default='alguem', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='colaborador',
            name='nome_mae',
            field=models.CharField(default='alguem', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='colaborador',
            name='nome_pai',
            field=models.CharField(default='alguem', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='colaborador',
            name='profissao',
            field=models.CharField(default='al', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='colaborador',
            name='profissao_conjuge',
            field=models.CharField(default='ass', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='colaborador',
            name='profissao_mae',
            field=models.CharField(default='hhh', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='colaborador',
            name='profissao_pai',
            field=models.CharField(default='aaaaa', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='colaborador',
            name='sexo',
            field=models.CharField(choices=[('MASCULINO', 'MASCULINO'), ('FEMININO', 'FEMININO'), ('OUTRO', 'OUTRO'), ('PREFERE_NAO_INFORMAR', 'PREFERE NAO INFORMAR')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='colaborador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrato', to='main.colaborador'),
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(max_length=50)),
                ('cep', models.CharField(max_length=8)),
                ('bairro', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endereco', to='main.colaborador')),
            ],
        ),
    ]
