# Generated by Django 4.2 on 2024-04-02 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0015_rename_tel_familia_colaborador_tel_auxiliar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referencias_Pessoais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('logradouro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('telefone', models.CharField(blank=True, max_length=15)),
                ('profissao', models.CharField(max_length=100)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Exp_Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=100)),
                ('logradouro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('telefone', models.CharField(blank=True, max_length=15)),
                ('funcao_inicial', models.CharField(max_length=100)),
                ('funcao_final', models.CharField(max_length=100)),
                ('salario_inicial', models.CharField(max_length=50)),
                ('salario_final', models.CharField(max_length=50)),
                ('data_admissao', models.DateField()),
                ('data_recisao', models.DateField()),
                ('motivo_recisao', models.TextField()),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Documentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_carteira_profissional', models.CharField(max_length=50)),
                ('serie', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('rg', models.CharField(max_length=50)),
                ('orgao_exp', models.CharField(max_length=50)),
                ('data_exp', models.DateField()),
                ('num_reservista', models.CharField(max_length=50)),
                ('serie_reservista', models.CharField(max_length=50)),
                ('reg_militar', models.CharField(max_length=100)),
                ('titulo_eleitor', models.CharField(max_length=50)),
                ('zona_eleitoral', models.CharField(max_length=50)),
                ('secao_eleitoral', models.CharField(max_length=50)),
                ('pis_pasep', models.CharField(max_length=50)),
                ('habilitacao', models.CharField(max_length=50)),
                ('data_emissao_habilitacao', models.DateField()),
                ('categoria_habilitacao', models.CharField(max_length=5)),
                ('banco', models.CharField(max_length=50)),
                ('agencia', models.CharField(max_length=50)),
                ('conta', models.CharField(max_length=50)),
                ('tipo_pix', models.CharField(choices=[('CPF', 'CPF'), ('EMAIL', 'EMAIL'), ('NUM_TELEFONE', 'NUM_TELEFONE'), ('CHAVE_ALEATORIA', 'CHAVE ALEATORIA')], max_length=50)),
                ('pix', models.CharField(max_length=50)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Desenvolvimento_Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ensino_fundamental', models.CharField(choices=[('COMPLETO', 'COMPLETO'), ('INCOMPLETO', 'INCOMPLETO')], max_length=50)),
                ('fundamental_instituicao', models.CharField(max_length=100)),
                ('fundamental_ano_conclusao', models.CharField(max_length=4)),
                ('ensino_medio', models.CharField(choices=[('COMPLETO', 'COMPLETO'), ('INCOMPLETO', 'INCOMPLETO')], max_length=50)),
                ('medio_instituicao', models.CharField(max_length=100)),
                ('medio_ano_conclusao', models.CharField(max_length=4)),
                ('informatica_nivel', models.CharField(choices=[('BASICO', 'BASICO'), ('INTERMEDIARIO', 'INTERMEDIARIO'), ('AVANCADO', 'AVANCADO')], max_length=50)),
                ('informatica_instituicao', models.CharField(max_length=100)),
                ('informatica_ano_conclusao', models.CharField(max_length=4)),
                ('contabilidade_nivel', models.CharField(max_length=100)),
                ('contabilidade_instituicao', models.CharField(max_length=100)),
                ('contabilidade_ano_conclusao', models.CharField(max_length=4)),
                ('administracao_nivel', models.CharField(max_length=100)),
                ('administracao_instituicao', models.CharField(max_length=100)),
                ('administracao_ano_conclusao', models.CharField(max_length=4)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Canal_Divulgacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal_divulgacao', models.CharField(choices=[('INSTITUICAO_ENSINO', 'INSTITUICAO DE ENSINO'), ('AGENCIA_EMPREGO', 'AGENCIA DE EMPREGO'), ('INDICACAO', 'INDICACAO'), ('JORNAL', 'JORNAL'), ('OUTROS', 'OUTROS')], max_length=100)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
