# Generated by Django 4.2 on 2024-04-26 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_referencias_pessoais_exp_profissional_documentacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='upload_contrato',
            field=models.FileField(upload_to='contratos'),
        ),
    ]
