# Generated by Django 4.2 on 2024-04-26 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_contrato_upload_contrato'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contrato',
            old_name='upload_contrato',
            new_name='contrato',
        ),
    ]
