# Generated by Django 4.2 on 2024-08-06 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_rename_upload_contrato_contrato_contrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='colaborador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrato', to='main.colaborador'),
        ),
    ]
