# Generated by Django 4.2 on 2025-03-07 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0019_alter_contrato_colaborador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colaborador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='colaborador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrato', to='main.colaborador'),
        ),
    ]
