# Generated by Django 4.2 on 2025-06-06 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_colaborador_user_alter_contrato_colaborador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='departamento',
            field=models.TextField(choices=[('FINANCEIRO', 'FINANCEIRO'), ('CENTRAL_ATENDIMENTO', 'CENTRAL DE ATENDIMENTO'), ('CENTRAL_INADIMPLENCIA', 'CENTRAL DE INADIMPLENCIA'), ('COBRANCA', 'COBRANÇA'), ('CONTROLE_QUALIDADE', 'CONTROLE DE QUALIDADE'), ('REAL_CREDIT', 'REAL CREDIT'), ('RELACIONAMENTO', 'RELACIONAMENTO'), ('COMERCIAL', 'COMERCIAL'), ('RH', 'RH'), ('DEP_PESSOAL', 'DEPARTAMENTO PESSOAL'), ('JURIDICO', 'JURIDICO'), ('CONTABIL', 'CONTABIL'), ('CENTRAL_VENDAS', 'CENTRAL DE VENDAS'), ('SUPORTE_ADM', 'SUPORTE ADM'), ('FRANQUIAS_DISTRIBUIDORES', 'FRANQUIAS / DISTRIBUIDORES'), ('GERENCIA_CORPORATIVA', 'GERENCIA CORPORATIVA'), ('DIRETORIA_EXECUTIVA', 'DIRETORIA EXECUTIVA'), ('INFORMATICA', 'INFORMÁTICA'), ('MARKETING', 'MARKETING'), ('CERTIFICADO_DIGITAL', 'CERTIFICADO DIGITAL')], default='', max_length=150),
        ),
    ]
