# Generated by Django 4.2 on 2025-06-06 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_colaborador_departamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='cpf_mae',
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='cpf_pai',
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='estado_naturalidade',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='naturalidade',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='nome_conjuge',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='nome_mae',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='nome_pai',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='profissao',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='profissao_conjuge',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='profissao_mae',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='profissao_pai',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
